package:
   name: intake-solr
   version: 0.0.2

source:
   path: ..

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt
  noarch: python

requirements:
  build:
    - python
    - jinja2
  run:
    - intake
    - python
    - pysolr
    - requests-kerberos

test:
  source_files:
    - tests
  requires:
    - pytest
    - pytest-cov
    - coverage
  commands:
    - py.test --verbose --cov=intake_solr tests

about:
  home: https://github.com/ContinuumIO/intake-solr
  license: BSD
  license_file: LICENSE
  summary: |
    SOLR plugin for Intake
